name: solprice-hourly
on:
  schedule:
    - cron: "0 * * * *"   # run at the top of every hour
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python fetch_price.py
        env:
          IFTTT_KEY: cLcVxJK2s0l_FF-5UNwjNq
          IFTTT_EVENT: sol_price_log
